global:
  scrape_interval:     10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: minio
#    metrics_path: /minio/v2/metrics/cluster
#    metrics_path: /minio/v2/metrics/node
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
      - targets: 
        - minio:9000
