
volumes:
  data:

services:
  minio:
    image: minio/minio:latest
    command: server /data
    volumes:
    - data:/data
    ports:
    - 9000:9000
    environment:
      MINIO_ROOT_USER: $(minio_root_user:-admin)
      MINIO_ROOT_PASSWORD: $(minio_root_password:-admin123)
      MINIO_PROMETHEUS_AUTH_TYPE: public

  console:
    image: minio/console:latest
    command: server
    env_file: 
    - .env.local
    environment:
      CONSOLE_MINIO_SERVER: http://minio:9000
      CONSOLE_PROMETHEUS_URL: http://prometheus:9090
    ports:
    - 8080:9090

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus:/etc/prometheus:ro
    ports:
    - 9090:9090

  mc:
    image: minio/mc
    volumes:
    - ./.mc:/root/.mc
    - ./policy:/policy
